### PR TITLE
Fix Initstate

### LINKED ISSUE #77: Re-enable initState cached loading
The feature works really well for fast loading, but there is a reactive store bug.

initState breaks active accounts for some reason.

Disabled it for now. https://github.com/thousandetherhomepage/ketherhomepage/commit/a1f0baa6553504e96897949999b2c8baf2541f83#diff-2886ae8dc0ffc0d351cc2e75fe977ac32d0067891113a6ec3c25c3761edb9633R161

### PR DESCRIPTION
**Pull request by mveytsman**
Closes #77 

This is almost done but needs a little more love / pairing.

Note that we had called `initState` before here: https://github.com/thousandetherhomepage/ketherhomepage/compare/ketherview...initstate?expand=1#diff-14af39602d66d245fb69d4848931be37bcb6fe9004720fbeff2c2b298d9a888cR164 -- this was just deleted in this branch, we still do it in master.

The issue is that `setContract(s)` is called when the wallet is connected, which would re-init the state and break everything.

I made the initial state only load on network change. I also only use the KetherView loading if we're changing networks. 

Note also that we're calling `loadAds` again after connecting the wallet (which I made sure doesn't do anything except try to load events see above). We will also be subscribing to contracts when the wallet is connected, which may lead to double events?

We still need to 
- [ ] make sure `wrapped` is set right on events coming in (I regenerated initState.json to contain the field)
- [ ] Refactor the `isNFT` stuff we have conflicting with `wrapped`
- [ ] we attribute you your NFT ads if you connect / change wallets

### CODE REVIEW

File: components/App.vue [hunk 1]
```diff
@@ -133,7 +133,7 @@ export default {
       this.networkConfig = deployConfig[this.activeNetwork];
       if (this.networkConfig) {
         const {contract, ketherNFT, ketherView} = loadContracts(this.networkConfig, this.provider)
-        this.setContracts(contract, ketherNFT, ketherView);
+        await this.setContracts(this.activeNetwork, contract, ketherNFT, ketherView);
```
Comment (mveytsman) [inline components/App.vue:136]: fwiw `setContracts` can get the activeNetwork from the contract but I wasn't sure if it would give us an extra network call.

**Comment by shazow** [comment]
Looks extremely plausible! You were able to reproduce the bug before right?

File: components/App.vue [hunk 2]
```diff
@@ -168,12 +170,15 @@ export default {
       this.contract.on('error', function(err) {
         console.error("Contract subscription error:", err);
       });
-
+      // FIXME this will trigger a second reload (using ketherview) when the user connects their wallet
```
Comment (shazow) [inline components/App.vue:173]: Is this blocking?
